# Generated by Django 5.0.2 on 2024-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
    ]
