<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
=======
'use client';

import { Inter } from 'next/font/google';
import './globals.css';
import axios from 'axios';
import { QueryClient, QueryClientProvider } from 'react-query';
import StoreProvider from '@/app/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

axios.defaults.baseURL = 'http://localhost:8000/';
axios.defaults.xsrfCookieName = 'csrftoken';
axios.defaults.xsrfHeaderName = 'X-CSRFToken';
axios.defaults.withCredentials = true;

const client = new QueryClient();

export default function RootLayout({ children }: ILayout) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/img/favicon.ico" />
				<title>RestInPist</title>
			</head>
			<QueryClientProvider client={client}>
				<StoreProvider>
					<body className={inter.className}>{children}</body>
				</StoreProvider>
			</QueryClientProvider>
		</html>
	);
>>>>>>> 50e42646dc042b1a36895116f7b7601ce7d97a90
}
